2019-08-28 14:18:07,784 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 14:18:34,377 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 14:56:17,998 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 15:03:49,236 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 15:16:05,015 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 15:17:57,620 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 15:18:19,638 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 15:19:13,928 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-08-28 15:19:45,387 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-01 15:44:08,209 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-08 15:21:03,001 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-08 15:41:10,556 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-08 15:43:53,942 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-08 15:50:24,093 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-26 21:12:25,762 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2019-09-29 17:20:57,333 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:35]
2020-07-12 15:33:06,133 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:57]
2020-07-12 16:47:03,078 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:57]
2020-07-12 16:51:26,252 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:57]
2020-07-12 19:22:21,105 INFO: Microblog startup [in D:\py\virFlask\app\__init__.py:57]
2021-09-14 10:37:20,151 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-14 10:55:30,593 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-16 09:18:26,618 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-21 11:17:10,569 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-21 17:27:26,624 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-28 18:01:34,282 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-28 18:12:57,998 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 11:46:45,076 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 14:24:57,633 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 14:27:32,603 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 14:58:41,623 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 16:18:55,647 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 16:25:39,451 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 17:27:43,636 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 17:30:31,671 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 17:35:12,207 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 17:43:06,809 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 17:49:04,198 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 17:55:40,121 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-29 18:03:15,167 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-30 08:44:57,286 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-30 08:44:59,082 ERROR: Exception on /index [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\vd\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\vD\app\routes.py", line 44, in index
    return render_template('index.html', title=title, posts=posts.items,
  File "d:\py\vd\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\vd\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\vd\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\vd\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\vD\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\py\vD\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'html'
    {% block body -%}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 22, in block 'body'
    {% block navbar %}
  File "D:\py\vD\app\templates\base.html", line 27, in block 'navbar'
    <li><a href="{{ url_for('upload') }}">uploads..</a></li>
  File "d:\py\vd\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\py\vd\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "d:\py\vd\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'upload'. Did you forget to specify values ['filename']?
2021-09-30 08:46:47,590 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-30 08:46:53,080 ERROR: Exception on /index [GET] [in d:\py\vd\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\py\vd\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\py\vd\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "d:\py\vd\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "D:\py\vD\app\routes.py", line 44, in index
    return render_template('index.html', title=title, posts=posts.items,
  File "d:\py\vd\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\py\vd\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\py\vd\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\py\vd\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\py\vD\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\py\vD\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'html'
    {% block body -%}
  File "d:\py\vd\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 22, in block 'body'
    {% block navbar %}
  File "D:\py\vD\app\templates\base.html", line 27, in block 'navbar'
    <li><a href="{{ url_for('upload', filename=rrrr.png) }}">uploads..</a></li>
  File "d:\py\vd\lib\site-packages\jinja2\environment.py", line 474, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'rrrr' is undefined
2021-09-30 08:47:35,426 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-30 09:22:59,827 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-30 12:14:47,939 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
2021-09-30 12:15:31,977 INFO: Microblog startup [in D:\py\vD\app\__init__.py:57]
